//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int ID { get; set; }
        public int AnswerTypeID { get; set; }
        public string QuestionText { get; set; }
        public string AllAnswers { get; set; }
        public string AnswerLine { get; set; }
    
        public virtual AnswerType AnswerType { get; set; }
    }
}
